"""Render a ScoredAudit into a Markdown report, including an optional
'cost of neglect' estimate and an optional competitor comparison.

The cost-of-neglect figure uses a commonly cited rule of thumb (roughly
7% conversion lost per extra second of load time, popularized by industry
studies from Google/Akamai/Deloitte over the years). It is an estimate
with a named, adjustable assumption, not a measured fact about this
specific site — the report says so explicitly, because presenting it as
a precise number would be a claim this tool cannot actually verify.
"""

from __future__ import annotations

from dataclasses import dataclass

from .scoring import ScoredAudit

CONVERSION_LOSS_PER_EXTRA_SECOND = 0.07  # commonly cited estimate, not a measurement


@dataclass(frozen=True)
class NeglectAssumptions:
    extra_load_seconds: float
    monthly_visits: int
    baseline_conversion_rate: float
    average_order_value: float


def estimate_cost_of_neglect(assumptions: NeglectAssumptions) -> dict:
    lost_conversion_share = min(1.0, assumptions.extra_load_seconds * CONVERSION_LOSS_PER_EXTRA_SECOND)
    baseline_orders = assumptions.monthly_visits * assumptions.baseline_conversion_rate
    lost_orders = baseline_orders * lost_conversion_share
    lost_revenue = lost_orders * assumptions.average_order_value
    return {
        "lost_conversion_share": round(lost_conversion_share, 4),
        "estimated_lost_orders_per_month": round(lost_orders, 1),
        "estimated_lost_revenue_per_month": round(lost_revenue, 2),
    }


def render_report(
    audit: ScoredAudit,
    *,
    neglect: dict | None = None,
    competitors: list[ScoredAudit] | None = None,
) -> str:
    lines = [f"# Technical audit — {audit.domain}", "", f"**Overall score: {audit.score}/100**", ""]

    for label, bucket in (("Critical", audit.critical), ("High priority", audit.high), ("Medium priority", audit.medium)):
        if not bucket:
            continue
        lines.append(f"## {label}")
        for item in bucket:
            lines.append(f"- **{item.label}** — {item.detail}")
        lines.append("")

    if audit.passed:
        lines.append("## Passing")
        for item in audit.passed:
            lines.append(f"- {item.label} — {item.detail}")
        lines.append("")

    if neglect:
        lines += [
            "## Estimated cost of neglect",
            "",
            "This is an estimate based on a commonly cited industry rule of thumb "
            f"(~{CONVERSION_LOSS_PER_EXTRA_SECOND:.0%} conversion lost per extra second of load time), "
            "not a measurement of this specific store. Treat it as a directional argument, not a guarantee.",
            "",
            f"- Estimated lost orders/month: {neglect['estimated_lost_orders_per_month']}",
            f"- Estimated lost revenue/month: ${neglect['estimated_lost_revenue_per_month']:,.2f}",
            "",
        ]

    if competitors:
        lines.append("## Competitor comparison")
        lines.append("")
        lines.append("| Domain | Score |")
        lines.append("| --- | --- |")
        lines.append(f"| **{audit.domain} (this site)** | **{audit.score}** |")
        for competitor in competitors:
            lines.append(f"| {competitor.domain} | {competitor.score} |")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by SiteDoctor — an automated technical audit, not a substitute for a manual review._")
    return "\n".join(lines) + "\n"
