# These are supported funding model platforms

github: # TODO: add your GitHub Sponsors username, e.g. HumbleDrummer
ko_fi: # TODO: add your Ko-fi username
custom: # TODO: add a URL, e.g. your Gumroad product page or Buy Me a Coffee link
